### ISSUE TITLE
ksi-stats-scripts

### ISSUE THREAD

**Issue by arturparkhisenko** [Zengineers/Academy#20]
**Who do:** @Dmytraw 
**Who check:** @DenisKuznecov 
**What:**
- [x] angular1, $http service
- [x] скрипт который будет отвечать за ajax отправку формы и тд, с попапом или нотификацией об отправке или ошибке, связь этого всего с backend (тут уже должна быть коллаборация с @borodinchik )
- [x] Авторизация OAuth github/google :octocat: что бы была защита от повторных голосований
- [x] валидация данных на фронтенде
- [x] писать с фейковым бекендом по началу, потом на пхпшный а потом на firebase :fire: 

**When:** в четверг на следующей неделе

**Comment by arturparkhisenko** [comment]
@Katanji я забыл, ты сюда напиши про идею с аккордионом, либо закоммить пример)

**Comment by Katanji** [comment]
@arturparkhisenko ![2](https://cloud.githubusercontent.com/assets/18643330/15424537/db56fd5c-1e8b-11e6-9cc0-e8a2f3259c5a.jpg)

**Comment by DenisKuznecov** [comment]
Дима еще не делал?

**Comment by Katanji** [comment]
нет

**Comment by alexakuna** [comment]
Мб сделать не одним окном а в несколько этапов?
То есть:
1. Окно с текстом о необходимости заполнить форму и кнопкой, допустим START/GO. После нажатия появляется  первая часть формы.  
2. Здесь два инпута имя и фамилия( по одному имени как то плохо отслеживать кто это именно) , под инпутами кнопка NEXT STEP ну и что то в виде прогресс-бара для индикации шагов ну и после клика по кнопке появляется некст форма.
3. Здесь инпут с выпадающим списком языков программирования и было бы прикольно прикрутить поиск, или выбрал с списка или через поиск( ну это если список огромный будет ).
И в этом же окне под инпутом сделать шкалу знания в данном языке в виде звездочек . Ну и собсно кнопка типа FINISH, или просто ОТПРАВИТЬ)))
А там если идея нра можно допилить инпут с списком каких ли бо фреймфорков связаных с выбранным языком.
   Как то так)

**Comment by arturparkhisenko** [comment]
@alexakuna @Dmytraw https://www.typeform.com/ вот что мне нравится, остальное всё шлак неюзабельный) ну есть что-то похожее на материале, и можно самому запилить, если сделаете, вам все спасибо скажут)

**Comment by alexakuna** [comment]
да, красиво

**Comment by Dmytraw** [comment]
я хочу на материале.хочу больше хардкора.
